name: ci-cd

on: pull_request, push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest

  upload_zip:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Zip the code
        run: |
          zip -r release.zip . -x ".git/*" ".github/*" ".gitignore"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-release
          path: release.zip